common = ['PAFWPD', 'PLPTIN', 'HLPTC', 'TCIRCD', 'WAFWTK', 'WRECIR']

unique = ['WGSL', 'WLPTC', 'ZINST109', 'ZINST72', 'HHPDRNB', 'KZROD23', 'CXEMPCM', 'UHPHDT', 'ZINST86', 'PCOND', 'PSG1', 'PSGLP', 'USUBMA', 'XPMOUT', 'PCTMT', 'UHPDRNA', 'QLOAD', 'WNETCH', 'SIGMAA', 'PHDTP', 'PAFWPS', 'PSG2', 'ZSGW3', 
'EHDTK', 'ZSGLER', 'WSGRCP1', 'XSEBAL', 'WFWPBY', 'UFUEL5', 'KZROD19', 'KZROD21', 'ZINST75', 'UFWPOUT', 'ZINST11', 'WCWAT', 'UHOLEG2', 'UCOOL', 'UFUEL1', 'UHPDRNB', 'DNBMRG', 'KBCDO8', 'UCOLEG2', 'BTV418', 'KZROD18', 
'ZINST112', 'HLPDRNA', 'KZROD20', 'WSDMP', 'ZSGW2', 'HHPTEX', 'HLPDRNB', 'HCVWL', 'WCPLN2', 'VOID', 'ZINST39', 'HAFWTB', 'PHPHOUT', 'ZPRZSP', 'BFWBYI', 'KZROD24', 'ZINST43', 'BFV13', 'XPEBAL', 'ZINST51', 'UOVER', 
'XSMBAL', 'WHDTP', 'WSGRCP2', 'HHPDRNA', 'WCPLN3', 'KZBANK3', 'BFWBYP', 'ZHDTK', 'ULPDRNB', 'WCHGNO', 'ZINST80', 'WSTMFWE', 'FEIHDP', 'XSEOUT', 'CBVOLM', 'ZSGLEI', 'ZINST87', 'ZINST53', 'ECOND', 'ZINST78', 'PCVRT', 
'ZINST99', 'ZHDTKL', 'QNET', 'PTIN', 'KZROD22', 'ZCOND', 'WCPLN1', 'KZROD17', 'ZINST57', 'ZINST26', 'UCHGUT', 'UAVLEG2', 'PNCGAS', 'PCVSG', 'CVRDC', 'ULPHCD', 'PTINWM', 'WSURGE', 'ECVWL', 'UCNDS', 'ZINST74', 'UFUEL11',
 'ZINST60', 'FCWP', 'ECVSG(재미)', 'KBCDO22', 'UCOND', 'ZINST13', 'ZINST79', 'HHPRH', 'ZINST81', 'UDHOCO1', 'ULPDRNA', 'ZSGNOR1']

#지울 것 = 'KZROD23','XPMOUT', 'XSEBAL','KZROD19', 'DNBMRG', 'KBCDO8', 'KZROD18', 'KZROD20', 'KZROD24', 'XPEBAL', 'UOVER', 'XSMBAL', 'KZBANK3', 'WCHGNO', 'XSEOUT', 'KZROD22', 'KZROD17', 'CVRDC'

final_param = ['PAFWPD', 'PLPTIN', 'HLPTC', 'TCIRCD', 'WAFWTK', 'WRECIR', 'WGSL', 'WLPTC', 'ZINST109', 'ZINST72', 'HHPDRNB', 'CXEMPCM', 'UHPHDT', 'ZINST86', 'PCOND', 'PSG1', 'PSGLP', 'USUBMA', 'PCTMT', 'UHPDRNA', 'QLOAD', 'WNETCH', 'SIGMAA', 'PHDTP', 'PAFWPS', 'PSG2', 'ZSGW3', 
'EHDTK', 'ZSGLER', 'WSGRCP1', 'WFWPBY', 'UFUEL5', 'ZINST75', 'UFWPOUT', 'ZINST11', 'WCWAT', 'UHOLEG2', 'UCOOL', 'UFUEL1', 'UHPDRNB', 'UCOLEG2', 'BTV418', 
'ZINST112', 'HLPDRNA', 'WSDMP', 'ZSGW2', 'HHPTEX', 'HLPDRNB', 'HCVWL', 'WCPLN2', 'VOID', 'ZINST39', 'HAFWTB', 'PHPHOUT', 'ZPRZSP', 'BFWBYI', 'ZINST43', 'BFV13', 'ZINST51', 
'WHDTP', 'WSGRCP2', 'HHPDRNA', 'WCPLN3', 'BFWBYP', 'ZHDTK', 'ULPDRNB', 'ZINST80', 'WSTMFWE', 'FEIHDP', 'CBVOLM', 'ZSGLEI', 'ZINST87', 'ZINST53', 'ECOND', 'ZINST78', 'PCVRT', 
'ZINST99', 'ZHDTKL', 'QNET', 'PTIN', 'ZCOND', 'WCPLN1', 'ZINST57', 'ZINST26', 'UCHGUT', 'UAVLEG2', 'PNCGAS', 'PCVSG', 'ULPHCD', 'PTINWM', 'WSURGE', 'ECVWL', 'UCNDS', 'ZINST74', 'UFUEL11',
 'ZINST60', 'FCWP', 'ECVSG', 'KBCDO22', 'UCOND', 'ZINST13', 'ZINST79', 'HHPRH', 'ZINST81', 'UDHOCO1', 'ULPDRNA', 'ZSGNOR1', 'label']
